/**
 * Static indicator catalog — all 60 CDE indicators as hardcoded data.
 * Used as primary data source until the SQL migrations are run on Supabase.
 */
import type { IndicatorLibrary } from './indicatorLibraryService';

function makeId(code: string): string {
  return 'ind-' + code.toLowerCase().replace(/[^a-z0-9]/g, '-');
}

export const INDICATOR_CATALOG: IndicatorLibrary[] = [
  {
    indicator_id: makeId('COM-REACH-01'),
    code: 'COM-REACH-01',
    name: 'Website Unique Visitors',
    domain: 'communication' as const,
    definition: 'Number of unique individuals visiting project website during reporting period, measured via analytics platform using cookie/session identification.',
    rationale: 'Indicates breadth of digital reach and initial awareness generation. Essential baseline for digital communication strategy.',
    limitations: 'Does not measure depth of engagement, content consumption quality, or conversion to action. Subject to bot traffic and privacy settings affecting tracking accuracy.',
    interpretation_notes: 'Baseline should reflect pre-campaign traffic. Growth >50% indicates successful awareness campaigns. Compare against similar projects in same domain.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'analytics',
    collection_frequency: 'monthly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 1000,
    default_target: 10000,
  },
  {
    indicator_id: makeId('COM-REACH-02'),
    code: 'COM-REACH-02',
    name: 'Social Media Impressions',
    domain: 'communication' as const,
    definition: 'Total number of times project-related content appeared in social media feeds across all platforms (organic and paid), regardless of clicks or engagement.',
    rationale: 'Measures potential exposure and visibility of communication messages. Critical for understanding amplification effectiveness.',
    limitations: 'Impressions do not equal views or attention. Platform algorithms heavily influence distribution. Does not indicate message comprehension or acceptance.',
    interpretation_notes: 'Expect 10-30x multiplier from followers count. Paid promotion significantly increases impressions but may reduce engagement rate.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'analytics',
    collection_frequency: 'monthly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 5000,
    default_target: 100000,
  },
  {
    indicator_id: makeId('COM-REACH-03'),
    code: 'COM-REACH-03',
    name: 'Event Participants (In-person)',
    domain: 'communication' as const,
    definition: 'Number of individuals physically attending project-organized or co-organized communication events, verified through registration systems or attendance records.',
    rationale: 'Direct engagement indicator demonstrating ability to mobilize target audiences and create face-to-face communication opportunities.',
    limitations: 'Attendance does not guarantee active participation or learning outcomes. Quality of engagement varies significantly by event format and facilitation.',
    interpretation_notes: 'Typical EU project events range 30-200 participants. Academic events skew higher (100-300), policy events lower but higher quality (20-80).',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'per_activity',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 500,
  },
  {
    indicator_id: makeId('COM-REACH-04'),
    code: 'COM-REACH-04',
    name: 'Event Participants (Virtual)',
    domain: 'communication' as const,
    definition: 'Number of individuals attending project online events (webinars, virtual conferences, online workshops) tracked through platform analytics.',
    rationale: 'Measures digital event reach. Lower cost per participant than in-person but typically lower engagement depth.',
    limitations: 'High drop-off rates common (30-50% leave early). Passive attendance easy. Recorded sessions complicate unique participant counting.',
    interpretation_notes: 'Expect 2-5x higher registration than in-person, but 40-60% actual attendance rate. Engagement rate (questions, polls) typically 10-20% of attendees.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'analytics',
    collection_frequency: 'per_activity',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 1000,
  },
  {
    indicator_id: makeId('COM-ENG-01'),
    code: 'COM-ENG-01',
    name: 'Social Media Engagement Rate',
    domain: 'communication' as const,
    definition: 'Percentage of social media impressions that generated active engagement (likes, shares, comments, clicks) calculated as (total engagements / total impressions) × 100.',
    rationale: 'Indicates message resonance and content quality. More meaningful than raw reach for assessing communication effectiveness.',
    limitations: 'Algorithm changes affect baseline rates. Paid content typically has lower engagement rate than organic. Platform-specific norms vary widely.',
    interpretation_notes: 'EU project typical rates: LinkedIn 2-4%, Twitter 0.5-2%, Facebook 1-3%. Rates >5% indicate exceptional content. Rates <0.5% suggest poor targeting or content.',
    unit: 'percentage',
    aggregation_method: 'average',
    data_source: 'analytics',
    collection_frequency: 'monthly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 1,
    default_target: 3,
  },
  {
    indicator_id: makeId('COM-ENG-02'),
    code: 'COM-ENG-02',
    name: 'Newsletter Open Rate',
    domain: 'communication' as const,
    definition: 'Percentage of delivered newsletters that were opened by recipients, calculated as (unique opens / delivered emails) × 100, tracked via email marketing platform.',
    rationale: 'Measures subject line effectiveness and sender reputation. Indicates maintained interest from subscribed audience.',
    limitations: 'Apple Mail Privacy Protection inflates open rates. B2B audiences have higher rates than B2C. Time-of-send significantly affects rates.',
    interpretation_notes: 'EU project benchmarks: 20-30% good, 15-20% acceptable, <15% problematic. Academic audiences higher (25-35%), policy audiences lower (15-25%).',
    unit: 'percentage',
    aggregation_method: 'average',
    data_source: 'analytics',
    collection_frequency: 'per_activity',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 20,
    default_target: 30,
  },
  {
    indicator_id: makeId('COM-ENG-03'),
    code: 'COM-ENG-03',
    name: 'Average Session Duration (Website)',
    domain: 'communication' as const,
    definition: 'Mean time in minutes that visitors spend on project website per session, measured from landing to exit or timeout.',
    rationale: 'Indicates content relevance and engagement depth. Longer sessions suggest visitors finding valuable information.',
    limitations: 'Session timeout settings affect calculation. Does not measure active vs. idle time. Technical users may use site differently than general public.',
    interpretation_notes: 'Typical EU project sites: 2-4 minutes average. <1 minute suggests poor content relevance. >5 minutes indicates strong content or research usage.',
    unit: 'number',
    aggregation_method: 'average',
    data_source: 'analytics',
    collection_frequency: 'monthly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 2,
    default_target: 4,
  },
  {
    indicator_id: makeId('COM-AUD-01'),
    code: 'COM-AUD-01',
    name: 'Stakeholder Group Diversity',
    domain: 'communication' as const,
    definition: 'Number of distinct stakeholder categories reached through communication activities, based on predefined taxonomy (policymakers, practitioners, researchers, industry, civil society, public, consortium).',
    rationale: 'Ensures communication strategy reaches intended variety of audiences, not just echo chamber. Critical for systemic impact projects.',
    limitations: 'Counts categories, not individuals. Does not measure depth of reach within each category. Self-reported categorization may be imprecise.',
    interpretation_notes: 'Projects should target 3-5 stakeholder groups. Reaching all 7 is rare and may indicate lack of focus. Monitor whether priority groups are being reached.',
    unit: 'number',
    aggregation_method: 'max',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 2,
    default_target: 5,
  },
  {
    indicator_id: makeId('COM-PERC-01'),
    code: 'COM-PERC-01',
    name: 'Brand Recognition',
    domain: 'communication' as const,
    definition: 'Percentage of surveyed target audience members who can correctly identify project name, logo, or core message when prompted, measured via awareness survey.',
    rationale: 'Indicates communication cut-through and memorability. Essential for projects requiring sustained engagement or behavior change.',
    limitations: 'Requires survey infrastructure. Sample size and representativeness critical. Prompted recall easier than unprompted. Geographic and temporal decay significant.',
    interpretation_notes: 'Baseline typically near zero for new projects. 15-25% recognition after 1 year indicates successful awareness campaign. 40%+ exceptional.',
    unit: 'percentage',
    aggregation_method: 'latest',
    data_source: 'survey',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 5,
    default_target: 25,
  },
  {
    indicator_id: makeId('COM-PERC-02'),
    code: 'COM-PERC-02',
    name: 'Message Comprehension',
    domain: 'communication' as const,
    definition: 'Percentage of event participants or survey respondents who can accurately explain core project message or value proposition in own words, assessed against rubric.',
    rationale: 'Measures communication quality beyond reach. Tests whether audiences actually understand what project does and why it matters.',
    limitations: 'Requires qualitative assessment and scoring rubric. Labor-intensive. Small sample sizes common. Self-selection bias in respondents.',
    interpretation_notes: 'Comprehension typically 30-50% lower than awareness. 60%+ indicates exceptional message clarity. Track which message elements are most/least understood.',
    unit: 'percentage',
    aggregation_method: 'average',
    data_source: 'survey',
    collection_frequency: 'per_activity',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 30,
    default_target: 70,
  },
  {
    indicator_id: makeId('DIS-KNO-01'),
    code: 'DIS-KNO-01',
    name: 'Knowledge Assets Published',
    domain: 'dissemination' as const,
    definition: 'Number of structured knowledge products published and made accessible to target audiences (publications, guidelines, toolkits, datasets, policy briefs, training materials).',
    rationale: 'Core dissemination output. Represents project contribution to knowledge base and usability for stakeholders.',
    limitations: 'Counts outputs, not quality or impact. Does not measure actual usage. Publication does not guarantee discoverability or accessibility.',
    interpretation_notes: 'Typical EU project: 8-15 assets over lifecycle. Research projects higher (15-30), demonstration projects lower (5-10). Quality over quantity critical.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 20,
  },
  {
    indicator_id: makeId('DIS-KNO-02'),
    code: 'DIS-KNO-02',
    name: 'Open Access Publications',
    domain: 'dissemination' as const,
    definition: 'Number of peer-reviewed publications made available via open access channels (Gold, Green, or Diamond OA) within 6 months of publication.',
    rationale: 'EU mandate for publicly-funded research. Maximizes knowledge dissemination and societal return on investment.',
    limitations: 'OA status can change over time (embargo periods). Predatory OA journals complicate quality assessment. Does not measure actual readership.',
    interpretation_notes: 'Horizon Europe requires immediate OA for all publications. 100% OA should be target. Green OA (repository) acceptable if Gold unavailable.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 10,
  },
  {
    indicator_id: makeId('DIS-KNO-03'),
    code: 'DIS-KNO-03',
    name: 'Knowledge Asset Downloads',
    domain: 'dissemination' as const,
    definition: 'Total number of complete downloads of project knowledge products from project website, repositories, or publication platforms.',
    rationale: 'Indicates active knowledge seeking behavior. More meaningful than webpage views for assessing dissemination effectiveness.',
    limitations: 'Bots inflate numbers. Download does not equal reading or use. Multi-chapter documents may have partial downloads. Cannot track secondary distribution.',
    interpretation_notes: 'Expect 50-200 downloads per asset in first 6 months. Policy briefs 100-500, technical reports 20-100, datasets 10-50. Long tail effect significant.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'analytics',
    collection_frequency: 'monthly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 2000,
  },
  {
    indicator_id: makeId('DIS-KNO-04'),
    code: 'DIS-KNO-04',
    name: 'Citations in External Publications',
    domain: 'dissemination' as const,
    definition: 'Number of times project outputs are cited in external scholarly publications, policy documents, or professional reports, tracked via citation databases.',
    rationale: 'Gold standard for knowledge uptake in research communities. Indicates project findings deemed credible and useful by peers.',
    limitations: 'Time lag of 2-5 years for citations to accumulate. Discipline-specific norms vary widely. Non-academic impact not captured. Self-citations must be excluded.',
    interpretation_notes: 'Research projects: 50-200 citations over 5 years post-project is good. Policy-focused projects: 10-30 citations in gray literature. Patience required.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 100,
  },
  {
    indicator_id: makeId('DIS-TRA-01'),
    code: 'DIS-TRA-01',
    name: 'Training Sessions Delivered',
    domain: 'dissemination' as const,
    definition: 'Number of structured training activities delivered to target audiences (workshops, webinars, train-the-trainer sessions, masterclasses).',
    rationale: 'Active dissemination through capacity building. Indicates commitment to supporting knowledge application, not just publishing.',
    limitations: 'Counts sessions not participants. Does not measure learning outcomes. One-off training has limited lasting impact without follow-up.',
    interpretation_notes: 'Typical projects: 5-12 training sessions. Complex methodologies require more. Include both direct training and train-the-trainer multiplier events.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 15,
  },
  {
    indicator_id: makeId('DIS-TRA-02'),
    code: 'DIS-TRA-02',
    name: 'Trainees Reporting Improved Understanding',
    domain: 'dissemination' as const,
    definition: 'Percentage of training participants who report improved understanding of topic via post-training survey (5-point Likert scale, aggregating "agree" and "strongly agree").',
    rationale: 'Measures training effectiveness and immediate learning outcomes. Essential for capacity building credibility.',
    limitations: 'Self-reported perception, not objective knowledge test. Social desirability bias inflates scores. Immediate assessment misses retention decay.',
    interpretation_notes: 'Expect 70-85% positive response for good training. <60% indicates delivery problems. Compare pre/post knowledge tests for robust evidence.',
    unit: 'percentage',
    aggregation_method: 'average',
    data_source: 'survey',
    collection_frequency: 'per_activity',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 70,
    default_target: 85,
  },
  {
    indicator_id: makeId('DIS-CAP-01'),
    code: 'DIS-CAP-01',
    name: 'Reusable Tools/Frameworks Created',
    domain: 'dissemination' as const,
    definition: 'Number of operational tools, methodologies, or frameworks developed by project that are designed for replication/adaptation by external users (software, templates, assessment frameworks).',
    rationale: 'Highest value dissemination outputs. Enable stakeholders to apply project knowledge independently. Multiplier effect potential.',
    limitations: 'Creation does not guarantee adoption. Usability and documentation quality critical. Maintenance and support requirements often underestimated.',
    interpretation_notes: 'Quality over quantity. 2-3 well-documented, actively maintained tools more valuable than 10 abandoned ones. Track adoption separately.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 5,
  },
  {
    indicator_id: makeId('DIS-CAP-02'),
    code: 'DIS-CAP-02',
    name: 'Stakeholder Networks Established',
    domain: 'dissemination' as const,
    definition: 'Number of formal or informal stakeholder networks, communities of practice, or professional groups established or significantly strengthened through project activities.',
    rationale: 'Sustainable dissemination mechanism beyond project lifetime. Creates infrastructure for continued knowledge exchange.',
    limitations: 'Network sustainability uncertain post-project. Counting methodology subjective. Network activity level varies widely. Attribute causality difficult.',
    interpretation_notes: 'Even 1-2 active networks represent success. Track network characteristics: size, activity level, governance. Plan sustainability from start.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 3,
  },
  {
    indicator_id: makeId('EXP-INT-01'),
    code: 'EXP-INT-01',
    name: 'Expressions of Interest',
    domain: 'exploitation' as const,
    definition: 'Number of documented, substantive expressions of interest from potential adopters, licensees, investors, or implementation partners regarding project outputs.',
    rationale: 'Early signal of exploitation potential. Indicates market/stakeholder appetite for project results. Pipeline metric for formal agreements.',
    limitations: 'Expression does not equal commitment. Requires follow-up conversion effort. Definition of "substantive" needs operationalization. Time-bound relevance.',
    interpretation_notes: 'Track source (industry vs public sector vs research), type of interest (adoption, licensing, investment), and conversion rate to formal agreements.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 25,
  },
  {
    indicator_id: makeId('EXP-INT-02'),
    code: 'EXP-INT-02',
    name: 'Formal Exploitation Agreements',
    domain: 'exploitation' as const,
    definition: 'Number of signed legal agreements for exploitation of project results (licensing, collaboration, commercialization, implementation contracts, spin-off creation).',
    rationale: 'Concrete exploitation outcome. Represents successful transition from research to application. Key performance indicator for innovation projects.',
    limitations: 'Agreement does not guarantee implementation or revenue. Some exploitation happens without formal agreements. Confidentiality limits public reporting.',
    interpretation_notes: 'Even 2-3 formal agreements represent project success. Track agreement type, financial terms, implementation timeline. Multi-year conversion cycle typical.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 5,
  },
  {
    indicator_id: makeId('EXP-IMP-01'),
    code: 'EXP-IMP-01',
    name: 'Implementations in Operational Settings',
    domain: 'exploitation' as const,
    definition: 'Number of documented instances where project outputs are deployed in real-world operational settings beyond project pilots (public services, commercial products, policy frameworks).',
    rationale: 'Ultimate exploitation goal: real-world application. Demonstrates project outputs are fit-for-purpose and deliver value.',
    limitations: 'Attribution challenges when project contributes to larger initiative. Implementation quality varies. Requires ongoing monitoring post-project.',
    interpretation_notes: 'Pilot-to-operational transition typically 2-4 years. Track implementation depth (pilot, partial, full), scale (local, regional, national), and sustainability.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 10,
  },
  {
    indicator_id: makeId('EXP-IMP-02'),
    code: 'EXP-IMP-02',
    name: 'Geographic Replication',
    domain: 'exploitation' as const,
    definition: 'Number of distinct countries or regions where project outputs have been adopted or adapted for implementation, beyond original project scope.',
    rationale: 'Measures transferability and scalability. Indicates outputs are not context-specific. EU projects expected to demonstrate cross-border relevance.',
    limitations: 'Replication depth varies (full adoption vs superficial adaptation). Cultural and regulatory context affects transferability. Tracking requires active monitoring.',
    interpretation_notes: 'Target 3-5 countries for projects with EU scope. Global projects should reach 8-12. Distinguish between consortium countries and external replication.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 1,
    default_target: 8,
  },
  {
    indicator_id: makeId('EXP-POL-01'),
    code: 'EXP-POL-01',
    name: 'Policy References',
    domain: 'exploitation' as const,
    definition: 'Number of policy documents, strategies, regulations, or legislative texts that explicitly reference or incorporate project findings or recommendations.',
    rationale: 'Highest-level policy exploitation. Indicates project shaped policy discourse and decision-making. Strong evidence of societal impact.',
    limitations: 'Reference does not equal adoption or implementation. Attribution difficult with multiple evidence sources. Time lag can be 3-7 years. Geographic scope matters.',
    interpretation_notes: 'Even 1-2 policy references at EU or national level is significant success. Track document type (strategy vs regulation), implementation status, policy level.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 5,
  },
  {
    indicator_id: makeId('EXP-ECO-01'),
    code: 'EXP-ECO-01',
    name: 'Jobs Created/Safeguarded',
    domain: 'exploitation' as const,
    definition: 'Number of full-time equivalent (FTE) jobs created or safeguarded through commercial exploitation of project results (spin-offs, licensing leading to production, service delivery).',
    rationale: 'Economic impact indicator. Demonstrates employment and economic growth resulting from project innovation.',
    limitations: 'Attribution extremely challenging. Timeframe must be specified. Temporary vs permanent jobs. Requires counterfactual assessment. Self-reported data.',
    interpretation_notes: 'Even 10-20 jobs is meaningful for research projects. Innovation projects target 50-100+. Distinguish direct jobs (spin-offs) from indirect (supply chain).',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 100,
  },
  {
    indicator_id: makeId('EXP-ECO-02'),
    code: 'EXP-ECO-02',
    name: 'Revenue from Exploitation',
    domain: 'exploitation' as const,
    definition: 'Total revenue (EUR) generated through commercial exploitation of project intellectual property or results (licensing fees, sales, service contracts).',
    rationale: 'Financial sustainability and return on investment indicator. Demonstrates market validation and economic viability of project outputs.',
    limitations: 'Confidentiality restrictions limit reporting. Multi-year revenue streams complicate attribution. Does not capture non-monetary value. Currency fluctuations.',
    interpretation_notes: 'Public sector projects: licensing fees 10-50k EUR. Commercial projects: target 200k-1M EUR within 3 years post-project. Track revenue trajectory.',
    unit: 'currency',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 1000000,
  },
  {
    indicator_id: makeId('COM-REACH-05'),
    code: 'COM-REACH-05',
    name: 'Press Releases Distributed',
    domain: 'communication' as const,
    definition: 'Number of formal press releases issued through recognised distribution channels (wire services, institutional press offices, targeted media lists) during the reporting period.',
    rationale: 'Measures proactive media engagement and structured outreach to journalists and news outlets. Indicates commitment to translating project milestones into newsworthy narratives.',
    limitations: 'Distribution does not guarantee pickup or publication. Quality and newsworthiness of content varies. Wire service reach metrics may overstate actual journalist engagement.',
    interpretation_notes: 'Typical EU projects issue 4-8 press releases over the project lifecycle, aligned with major milestones. Track pickup rate separately to assess effectiveness.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 10,
  },
  {
    indicator_id: makeId('COM-REACH-06'),
    code: 'COM-REACH-06',
    name: 'Media Mentions / Press Coverage',
    domain: 'communication' as const,
    definition: 'Number of distinct media articles, broadcasts, or online news pieces that mention the project by name or reference its key outputs, tracked via media monitoring services.',
    rationale: 'Indicates earned media reach and third-party validation of project relevance. Earned coverage carries higher credibility than self-published content.',
    limitations: 'Monitoring tools may miss niche or non-English outlets. Sentiment and accuracy of coverage not captured by count alone. Distinguishing substantive mentions from passing references is subjective.',
    interpretation_notes: 'EU-funded projects typically achieve 10-50 media mentions. National/regional outlets more common than international. Track tier (national vs local) and sentiment for richer analysis.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'analytics',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 50,
  },
  {
    indicator_id: makeId('COM-ENG-04'),
    code: 'COM-ENG-04',
    name: 'Newsletter Click-Through Rate',
    domain: 'communication' as const,
    definition: 'Percentage of newsletter recipients who clicked at least one link within the email, calculated as (unique clicks / delivered emails) x 100, tracked via email marketing platform.',
    rationale: 'Measures content relevance and call-to-action effectiveness beyond simple opens. Indicates audience willingness to engage further with project outputs.',
    limitations: 'Click tracking can be blocked by security software. Single metric does not reveal which content drives clicks. Low rates may reflect layout issues rather than content quality.',
    interpretation_notes: 'Industry benchmark for research/NGO newsletters: 2-5% CTR. EU project newsletters achieving >5% indicate strong content-audience fit. Compare against open rate for funnel analysis.',
    unit: 'percentage',
    aggregation_method: 'average',
    data_source: 'analytics',
    collection_frequency: 'per_activity',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 2,
    default_target: 5,
  },
  {
    indicator_id: makeId('COM-ENG-05'),
    code: 'COM-ENG-05',
    name: 'Video Views',
    domain: 'communication' as const,
    definition: 'Total number of views of project-produced video content across all hosting platforms (YouTube, Vimeo, social media native video), counting views that exceed the platform minimum threshold.',
    rationale: 'Video is increasingly the primary content format for digital audiences. View counts indicate reach and accessibility of audiovisual communication outputs.',
    limitations: 'Platform definitions of a "view" differ (e.g., YouTube 30s, Facebook 3s). Autoplay and embedded views inflate counts. Does not measure comprehension or watch-through rate.',
    interpretation_notes: 'Project explainer videos: 500-5,000 views typical. Event recordings: 100-1,000. Viral potential is low for specialised content. Track average watch percentage for quality signal.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'analytics',
    collection_frequency: 'monthly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 10000,
  },
  {
    indicator_id: makeId('COM-ENG-06'),
    code: 'COM-ENG-06',
    name: 'Content Shares / Amplification',
    domain: 'communication' as const,
    definition: 'Total number of times project content is shared, retweeted, reposted, or forwarded by external users across all digital platforms, indicating organic amplification by the audience.',
    rationale: 'Shares represent the highest form of digital endorsement. Indicates audiences find content valuable enough to associate with their own networks and reputation.',
    limitations: 'Share counts may be inflated by consortium partners. Cannot distinguish genuine advocacy from courtesy shares. Private sharing (email, messaging) is untrackable.',
    interpretation_notes: 'Amplification ratio (shares per post) >2% is strong for niche content. Track which content types generate most shares to refine communication strategy.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'analytics',
    collection_frequency: 'monthly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 1000,
  },
  {
    indicator_id: makeId('COM-DIG-01'),
    code: 'COM-DIG-01',
    name: 'Website Pages per Session',
    domain: 'communication' as const,
    definition: 'Average number of distinct pages viewed per visitor session on the project website, as reported by the web analytics platform.',
    rationale: 'Measures content discoverability and internal navigation effectiveness. Higher values indicate visitors exploring multiple areas of project outputs.',
    limitations: 'Single-page applications may undercount. Bot traffic skews averages. High page counts may also indicate poor information architecture forcing excessive navigation.',
    interpretation_notes: 'EU project websites: 2-4 pages/session typical. Resource-rich sites may reach 5-7. If >8, investigate whether users are lost rather than engaged.',
    unit: 'number',
    aggregation_method: 'average',
    data_source: 'analytics',
    collection_frequency: 'monthly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 1.5,
    default_target: 4,
  },
  {
    indicator_id: makeId('COM-DIG-02'),
    code: 'COM-DIG-02',
    name: 'Social Media Follower Growth Rate',
    domain: 'communication' as const,
    definition: 'Percentage change in total social media followers across all project channels during the reporting period, calculated as ((new followers - unfollows) / starting followers) x 100.',
    rationale: 'Indicates sustained audience-building momentum and community growth. Differentiates between static and growing communication reach over time.',
    limitations: 'Follower counts include inactive accounts. Paid promotion artificially inflates growth. Early-stage projects show higher percentage growth from small bases. Platform-specific norms differ.',
    interpretation_notes: 'Healthy growth for EU project accounts: 3-8% per month in active periods. Stagnation (<1%) suggests content fatigue. Negative growth warrants strategy review.',
    unit: 'percentage',
    aggregation_method: 'average',
    data_source: 'analytics',
    collection_frequency: 'monthly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 5,
  },
  {
    indicator_id: makeId('COM-DIG-03'),
    code: 'COM-DIG-03',
    name: 'Multilingual Content Coverage',
    domain: 'communication' as const,
    definition: 'Number of languages in which key project communication materials (website, brochures, executive summaries) are made available, beyond the primary working language.',
    rationale: 'Demonstrates inclusivity and commitment to reaching diverse European audiences. Particularly relevant for projects with cross-border or pan-European ambitions.',
    limitations: 'Translation quality varies. Machine translation without review may undermine credibility. Not all materials need translation; prioritisation is key. Maintenance burden grows with each language.',
    interpretation_notes: 'Horizon Europe projects typically cover 3-6 EU languages. Interreg projects should cover all partner languages. English-only is insufficient for public-facing projects.',
    unit: 'number',
    aggregation_method: 'max',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 1,
    default_target: 6,
  },
  {
    indicator_id: makeId('COM-MAT-01'),
    code: 'COM-MAT-01',
    name: 'Communication Materials Produced',
    domain: 'communication' as const,
    definition: 'Total number of distinct communication materials produced during the reporting period, including brochures, factsheets, posters, flyers, project briefs, and roll-up banners.',
    rationale: 'Tracks communication output volume and readiness for events and outreach. Ensures sufficient collateral exists to support dissemination and engagement activities.',
    limitations: 'Counts production, not distribution or impact. Quality and design consistency not captured. Materials may become outdated quickly. Storage and version control can be challenging.',
    interpretation_notes: 'Projects typically produce 10-25 distinct materials over their lifecycle. Front-load production before major events. Ensure materials align with EU visual identity guidelines.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 25,
  },
  {
    indicator_id: makeId('COM-MAT-02'),
    code: 'COM-MAT-02',
    name: 'Infographics and Visual Assets Created',
    domain: 'communication' as const,
    definition: 'Number of professionally designed infographics, data visualisations, diagrams, or visual summary assets created to communicate project findings or processes to non-specialist audiences.',
    rationale: 'Visual content increases accessibility and shareability of complex research findings. Essential for policy and public audiences who may not engage with technical text.',
    limitations: 'Production cost and time investment significant. Effectiveness depends on design quality and data accuracy. Requires regular updating as findings evolve.',
    interpretation_notes: 'Aim for 5-10 key infographics aligned with major outputs. High-quality visuals generate 3-5x more social media engagement than text-only posts.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 10,
  },
  {
    indicator_id: makeId('DIS-KNO-05'),
    code: 'DIS-KNO-05',
    name: 'Policy Briefs Published',
    domain: 'dissemination' as const,
    definition: 'Number of concise, evidence-based policy briefs produced to translate project research findings into actionable recommendations for policymakers and institutional decision-makers.',
    rationale: 'Bridges the gap between research outputs and policy application. Demonstrates project commitment to knowledge translation beyond academic audiences.',
    limitations: 'Policy brief quality varies significantly. Production does not guarantee readership or influence. Requires understanding of policy cycles and decision-making contexts.',
    interpretation_notes: 'Target 2-4 policy briefs per project, timed to relevant policy windows. Co-creation with policy stakeholders increases uptake. Track distribution to targeted policymakers.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 5,
  },
  {
    indicator_id: makeId('DIS-KNO-06'),
    code: 'DIS-KNO-06',
    name: 'Best Practice Guides Produced',
    domain: 'dissemination' as const,
    definition: 'Number of structured best practice guides, handbooks, or implementation manuals published that synthesise project learnings into replicable methodologies for practitioners.',
    rationale: 'Maximises practical value of project results by packaging knowledge for direct application. Supports sustainability and replication beyond the project context.',
    limitations: 'Guide usability depends on target audience involvement in development. Shelf life limited without maintenance. Context-specificity may reduce transferability.',
    interpretation_notes: 'Aim for 2-5 guides targeting different practitioner groups. Co-develop with end users for relevance. Include case studies and step-by-step workflows.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 5,
  },
  {
    indicator_id: makeId('DIS-KNO-07'),
    code: 'DIS-KNO-07',
    name: 'Datasets Made Openly Available',
    domain: 'dissemination' as const,
    definition: 'Number of structured datasets deposited in recognised open data repositories (e.g., Zenodo, Figshare, national data portals) with FAIR-compliant metadata and persistent identifiers.',
    rationale: 'Fulfils EU Open Science requirements and maximises reuse potential of project-generated data. Enables secondary research and cross-project validation.',
    limitations: 'FAIR compliance levels vary. Data sensitivity may restrict openness. Curation and documentation effort is substantial. Download counts do not equal meaningful reuse.',
    interpretation_notes: 'Horizon Europe mandates data management plans with open-by-default principle. Target deposit within 6 months of data collection completion. Track DOI-based citations.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 8,
  },
  {
    indicator_id: makeId('DIS-KNO-08'),
    code: 'DIS-KNO-08',
    name: 'Technical Standards Contributed To',
    domain: 'dissemination' as const,
    definition: 'Number of formal technical standards, norms, or specifications (ISO, CEN, W3C, ETSI, or equivalent) to which the project has made documented contributions or submissions.',
    rationale: 'Standards represent the highest form of knowledge codification with binding or normative force. Contributions indicate project outputs have reached maturity for standardisation.',
    limitations: 'Standards development cycles are multi-year. Contribution acceptance is uncertain. Requires dedicated expertise and resources. Attribution may be diluted in committee processes.',
    interpretation_notes: 'Even 1-2 standards contributions is significant for most projects. Track stage of contribution (proposal, working draft, published standard). National standards bodies count.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 3,
  },
  {
    indicator_id: makeId('DIS-TRA-03'),
    code: 'DIS-TRA-03',
    name: 'Training Participants (Total)',
    domain: 'dissemination' as const,
    definition: 'Total number of individuals who participated in project-delivered training activities across all formats (in-person, virtual, blended), counted as unique participants per training event.',
    rationale: 'Aggregated reach metric for capacity-building activities. Complements session counts by showing actual human capital development scale.',
    limitations: 'Unique counting across multiple events is challenging. Attendance does not equal completion or learning. Participant demographics and seniority affect impact significance.',
    interpretation_notes: 'Target 100-500 trainees for mid-scale projects. Track repeat participants separately. Disaggregate by stakeholder type and geography for evaluation reporting.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'per_activity',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 500,
  },
  {
    indicator_id: makeId('DIS-TRA-04'),
    code: 'DIS-TRA-04',
    name: 'Post-Training Application Rate',
    domain: 'dissemination' as const,
    definition: 'Percentage of training participants who report applying learned skills or knowledge in their professional practice within 6 months of training, measured via follow-up survey.',
    rationale: 'Measures training transfer and real-world impact beyond classroom satisfaction. Demonstrates that capacity building leads to behaviour change and operational improvement.',
    limitations: 'Self-reported data subject to recall and desirability bias. Low response rates to follow-up surveys typical (20-40%). Attribution to specific training event difficult in complex work environments.',
    interpretation_notes: 'Application rates of 40-60% indicate effective training design. <30% suggests disconnect between content and professional needs. Include specific application examples in survey.',
    unit: 'percentage',
    aggregation_method: 'average',
    data_source: 'survey',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 20,
    default_target: 50,
  },
  {
    indicator_id: makeId('DIS-TRA-05'),
    code: 'DIS-TRA-05',
    name: 'Train-the-Trainer Multiplier Events',
    domain: 'dissemination' as const,
    definition: 'Number of training events delivered by individuals who were themselves trained by the project (second-generation or cascade training), indicating successful knowledge multiplication.',
    rationale: 'Demonstrates scalability and sustainability of capacity-building approach. Multiplier events extend project reach exponentially beyond direct training activities.',
    limitations: 'Quality control in cascade training is challenging. Content fidelity may degrade across generations. Tracking requires active network maintenance with trained trainers.',
    interpretation_notes: 'Even 3-5 multiplier events represent significant scaling success. Calculate multiplication factor (trainees reached indirectly / direct trainees). Document quality assurance mechanisms.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 8,
  },
  {
    indicator_id: makeId('DIS-OUT-01'),
    code: 'DIS-OUT-01',
    name: 'Conference Presentations Delivered',
    domain: 'dissemination' as const,
    definition: 'Number of oral presentations, poster sessions, or demonstrations delivered at external conferences, symposia, or professional gatherings by project team members presenting project results.',
    rationale: 'Indicates active participation in professional communities and peer-to-peer knowledge exchange. Conference settings provide credibility validation through peer selection processes.',
    limitations: 'Accepted presentations do not guarantee audience size or engagement. Travel budget constraints limit participation. Poster sessions reach fewer people than oral presentations.',
    interpretation_notes: 'Research-intensive projects: 15-30 presentations. Applied projects: 8-15. Prioritise high-impact, peer-reviewed conferences. Track audience size and feedback where available.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 25,
  },
  {
    indicator_id: makeId('DIS-OUT-02'),
    code: 'DIS-OUT-02',
    name: 'Invited Keynotes and Panels',
    domain: 'dissemination' as const,
    definition: 'Number of invited keynote speeches, panel participations, or expert roundtable contributions where project team members are specifically requested to share project expertise.',
    rationale: 'Invited contributions signal external recognition of project authority and relevance. Higher prestige than submitted presentations, indicating demand-side pull for project knowledge.',
    limitations: 'Invitations may reflect personal networks rather than project merit alone. Typically fewer opportunities than submitted presentations. Quality of event and audience varies.',
    interpretation_notes: 'Even 3-5 invited contributions over the project lifecycle indicates strong reputation building. High-level policy events and industry forums carry more weight than academic panels.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 8,
  },
  {
    indicator_id: makeId('DIS-OUT-03'),
    code: 'DIS-OUT-03',
    name: 'Cross-Project Collaborations',
    domain: 'dissemination' as const,
    definition: 'Number of formal or substantive collaborations established with other funded projects (joint publications, shared events, co-developed outputs, clustering activities) during the reporting period.',
    rationale: 'Demonstrates synergy creation and avoidance of duplication within funding programmes. EU funders increasingly value clustering and cross-fertilisation between projects.',
    limitations: 'Collaboration depth varies from token acknowledgement to deep integration. Coordination overhead can be significant. Measuring contribution balance between projects is subjective.',
    interpretation_notes: 'Horizon Europe cluster projects expect 3-8 cross-project collaborations. Participate in programme-level clustering events. Document joint outputs explicitly.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 8,
  },
  {
    indicator_id: makeId('DIS-CAP-03'),
    code: 'DIS-CAP-03',
    name: 'Open Source Contributions',
    domain: 'dissemination' as const,
    definition: 'Number of software tools, libraries, or code repositories made publicly available under recognised open-source licences (Apache 2.0, MIT, GPL, EUPL) with documentation and maintenance commitment.',
    rationale: 'Maximises reuse potential of technical outputs. Aligns with EU Open Source Strategy and FAIR principles for software. Enables community-driven improvement and sustainability.',
    limitations: 'Open sourcing without documentation or maintenance renders code unusable. Licence compatibility issues may limit adoption. Community building requires sustained effort beyond code release.',
    interpretation_notes: 'Even 1-2 well-documented, actively maintained repositories is valuable. Track stars, forks, and external pull requests as adoption signals. Use Software Heritage for archival.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 5,
  },
  {
    indicator_id: makeId('DIS-CAP-04'),
    code: 'DIS-CAP-04',
    name: 'Educational Curriculum Integrations',
    domain: 'dissemination' as const,
    definition: 'Number of formal integrations of project outputs into educational curricula at university, vocational, or professional development programme level, evidenced by syllabus references or course materials.',
    rationale: 'Represents deep, sustained knowledge transfer into educational systems. Ensures project knowledge reaches future generations of professionals and researchers.',
    limitations: 'Curriculum change cycles are slow (1-3 years). Attribution to a single project is often shared. Informal use in teaching harder to track than formal syllabus changes.',
    interpretation_notes: 'Even 1-2 curriculum integrations demonstrate significant educational impact. Erasmus+ projects should actively target this. Provide ready-to-use teaching modules to facilitate adoption.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'evidence-linked',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 5,
  },
  {
    indicator_id: makeId('EXP-INT-03'),
    code: 'EXP-INT-03',
    name: 'Letters of Support Collected',
    domain: 'exploitation' as const,
    definition: 'Number of formal letters of support, endorsement, or intent received from external organisations expressing commitment to use, adopt, or promote project results.',
    rationale: 'Tangible evidence of stakeholder buy-in and exploitation readiness. Letters provide documented proof of demand for evaluators and future funding applications.',
    limitations: 'Letters may be obtained through professional courtesy without genuine commitment. Quality and specificity of commitments varies. Follow-up on stated intentions is essential.',
    interpretation_notes: 'Collect 5-15 letters from diverse stakeholder types. Specific, time-bound commitments carry more weight than generic endorsements. Update letters annually to maintain relevance.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'basic' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 15,
  },
  {
    indicator_id: makeId('EXP-INT-04'),
    code: 'EXP-INT-04',
    name: 'Pilot Adoption Agreements',
    domain: 'exploitation' as const,
    definition: 'Number of signed agreements with external organisations to pilot, test, or trial project outputs in their operational context, including memoranda of understanding and pilot protocols.',
    rationale: 'Represents the critical bridge between interest and implementation. Pilots provide real-world validation data essential for scaling exploitation activities.',
    limitations: 'Pilot agreements may not progress to full adoption. Resource commitments from pilot partners vary. Pilot scope and duration affect comparability across projects.',
    interpretation_notes: 'Target 3-8 pilot agreements with diverse organisations. Define success criteria upfront. Document lessons learned from each pilot for exploitation strategy refinement.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 8,
  },
  {
    indicator_id: makeId('EXP-IMP-03'),
    code: 'EXP-IMP-03',
    name: 'Market Validation Studies Completed',
    domain: 'exploitation' as const,
    definition: 'Number of structured market analysis, feasibility study, or user needs assessment exercises completed to validate commercial or operational viability of project outputs.',
    rationale: 'Demonstrates evidence-based approach to exploitation planning. Reduces risk of misaligned exploitation strategies by grounding decisions in empirical market data.',
    limitations: 'Study quality and methodology vary. Rapidly changing markets may render findings obsolete. Positive validation does not guarantee commercial success. Cost of professional studies is significant.',
    interpretation_notes: 'Aim for 1-3 validation studies covering target markets/sectors. Include both demand-side (user willingness) and supply-side (competitive landscape) analysis.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 3,
  },
  {
    indicator_id: makeId('EXP-IMP-04'),
    code: 'EXP-IMP-04',
    name: 'Technology Readiness Level Advancement',
    domain: 'exploitation' as const,
    definition: 'Number of TRL levels advanced by the primary project technology or innovation during the project lifecycle, measured against the EU-standard 9-level TRL scale at project start and end.',
    rationale: 'Standard EU metric for innovation maturity progression. Demonstrates tangible progress from concept to market-ready solution. Required reporting metric for many Horizon Europe calls.',
    limitations: 'TRL assessment can be subjective without independent validation. Different components may advance at different rates. TRL is technology-focused and does not capture social or process innovation.',
    interpretation_notes: 'Typical Horizon Europe projects target 2-3 TRL advancement (e.g., TRL 3-4 to TRL 6-7). Document evidence for each TRL gate. Commission independent TRL assessment for credibility.',
    unit: 'number',
    aggregation_method: 'max',
    data_source: 'evidence-linked',
    collection_frequency: 'annually',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 3,
  },
  {
    indicator_id: makeId('EXP-IMP-05'),
    code: 'EXP-IMP-05',
    name: 'User Adoption Rate',
    domain: 'exploitation' as const,
    definition: 'Percentage of target users within pilot or early-adopter organisations who actively use project outputs after initial deployment, measured at defined intervals post-introduction.',
    rationale: 'Measures actual uptake beyond installation or access provision. Critical for distinguishing between theoretical availability and real-world integration into workflows.',
    limitations: 'Definition of "active use" must be operationalised per context. Measurement infrastructure may be intrusive. Adoption curves vary by innovation complexity and organisational culture.',
    interpretation_notes: 'Adoption rates >30% within 6 months indicate strong product-market fit. 10-30% is typical. <10% signals usability or relevance issues requiring intervention.',
    unit: 'percentage',
    aggregation_method: 'average',
    data_source: 'analytics',
    collection_frequency: 'quarterly',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 30,
  },
  {
    indicator_id: makeId('EXP-POL-02'),
    code: 'EXP-POL-02',
    name: 'Policy Consultations Participated In',
    domain: 'exploitation' as const,
    definition: 'Number of formal policy consultations, regulatory reviews, or governmental advisory processes in which project team members participated and submitted evidence or recommendations.',
    rationale: 'Demonstrates active engagement with policy-making processes. Participation provides direct channels to influence regulatory and strategic frameworks with project evidence.',
    limitations: 'Participation does not guarantee influence on final policy. Consultation processes are time-intensive. Project contributions may be diluted among many respondents.',
    interpretation_notes: 'Target 2-5 relevant consultations per year during active policy windows. EU-level consultations (European Commission) carry highest weight. Document specific contributions made.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'quarterly',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 8,
  },
  {
    indicator_id: makeId('EXP-POL-03'),
    code: 'EXP-POL-03',
    name: 'Standards Contributions Accepted',
    domain: 'exploitation' as const,
    definition: 'Number of project-originated contributions formally accepted into published or draft technical standards, norms, or regulatory frameworks by recognised standardisation bodies.',
    rationale: 'Represents the highest level of technical exploitation, where project knowledge becomes codified into binding or normative instruments with industry-wide or sector-wide application.',
    limitations: 'Acceptance timelines extend beyond typical project duration. Committee politics influence outcomes. Contribution specificity may be diluted through consensus processes.',
    interpretation_notes: 'Even a single accepted contribution to a major standard (ISO, CEN, ETSI) represents exceptional impact. Track contribution through standardisation pipeline stages.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'evidence-linked',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 3,
  },
  {
    indicator_id: makeId('EXP-ECO-03'),
    code: 'EXP-ECO-03',
    name: 'Investment / Funding Attracted Post-Project',
    domain: 'exploitation' as const,
    definition: 'Total value (EUR) of follow-on funding, venture capital, public grants, or institutional investment secured to further develop or scale project results after the initial funding period.',
    rationale: 'Strongest signal of exploitation viability and external confidence in project outputs. Demonstrates that results are compelling enough to attract independent financial commitment.',
    limitations: 'Attribution to original project versus team reputation is complex. Investment timelines may extend well beyond reporting periods. Confidentiality may limit disclosure.',
    interpretation_notes: 'Follow-on public funding (500k-2M EUR) common for successful projects. Private investment (100k-5M EUR) indicates commercial potential. Track leverage ratio (follow-on / original grant).',
    unit: 'currency',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 2000000,
  },
  {
    indicator_id: makeId('EXP-ECO-04'),
    code: 'EXP-ECO-04',
    name: 'Cost Savings Demonstrated',
    domain: 'exploitation' as const,
    definition: 'Total documented cost savings (EUR) achieved by adopting organisations through implementation of project outputs, calculated against established baselines using agreed methodology.',
    rationale: 'Provides compelling economic evidence for exploitation and scaling decisions. Cost savings are universally understood and highly persuasive for policymakers and industry adopters.',
    limitations: 'Baseline establishment and counterfactual reasoning challenging. Attribution to specific project outputs versus other operational changes is complex. Requires cooperation from adopting organisations.',
    interpretation_notes: 'Document methodology transparently. Even 50-100k EUR in demonstrated savings provides strong business case. Distinguish one-time savings from recurring annual savings.',
    unit: 'currency',
    aggregation_method: 'sum',
    data_source: 'evidence-linked',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 500000,
  },
  {
    indicator_id: makeId('EXP-ECO-05'),
    code: 'EXP-ECO-05',
    name: 'Patents or IP Registrations Filed',
    domain: 'exploitation' as const,
    definition: 'Number of patent applications, trademark registrations, design rights, or other formal intellectual property protections filed based on project-generated innovations or outputs.',
    rationale: 'Indicates commercially valuable innovation outputs. IP protection is a prerequisite for certain exploitation routes (licensing, spin-off creation, technology transfer).',
    limitations: 'Filing does not guarantee grant. Patent prosecution is multi-year and expensive. Not all innovations are patentable. Open science objectives may conflict with IP protection strategies.',
    interpretation_notes: 'Typical innovation projects: 1-3 patent filings. Software projects may prefer open-source licensing. Track filing status (provisional, national, PCT/EP). Align with consortium IP agreement.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 5,
  },
  {
    indicator_id: makeId('EXP-SUS-01'),
    code: 'EXP-SUS-01',
    name: 'Sustainability Plans Developed',
    domain: 'exploitation' as const,
    definition: 'Number of formal sustainability plans or business continuity strategies developed for key project outputs, specifying governance, funding models, and operational arrangements beyond the project period.',
    rationale: 'Demonstrates forward planning for post-project viability. EU evaluators specifically assess whether projects have credible plans for sustaining results beyond funding.',
    limitations: 'Plan existence does not guarantee execution. Plans may be aspirational without secured resources. Quality and specificity vary significantly across projects.',
    interpretation_notes: 'Develop sustainability plans for each key exploitable result. Include revenue model, governance structure, and risk mitigation. Review and update annually. Present to advisory board.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 5,
  },
  {
    indicator_id: makeId('EXP-SUS-02'),
    code: 'EXP-SUS-02',
    name: 'Continuation Partnerships Secured',
    domain: 'exploitation' as const,
    definition: 'Number of formal partnership agreements secured with organisations committed to maintaining, scaling, or further developing project outputs after the funded period concludes.',
    rationale: 'Provides structural foundation for sustainability. Partners bring resources, networks, and legitimacy needed to sustain results beyond initial project investment.',
    limitations: 'Partnership commitments may be contingent on conditions not yet met. Institutional priorities change. Partnership quality matters more than quantity.',
    interpretation_notes: 'Target 2-5 continuation partnerships with complementary capabilities. Prioritise partners with operational capacity and aligned strategic interests. Formalise with MoUs or contracts.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'advanced' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 5,
  },
  {
    indicator_id: makeId('EXP-SUS-03'),
    code: 'EXP-SUS-03',
    name: 'Spin-off Companies Created',
    domain: 'exploitation' as const,
    definition: 'Number of new legal entities (companies, cooperatives, social enterprises) established specifically to commercialise or operationalise project results, with direct lineage to project outputs.',
    rationale: 'Highest-impact exploitation outcome demonstrating commercial viability and entrepreneurial translation of research. Creates sustainable vehicles for long-term exploitation.',
    limitations: 'Spin-off creation is resource-intensive and high-risk. Survival rates for research spin-offs are 50-60% at 5 years. Requires entrepreneurial talent beyond research capabilities.',
    interpretation_notes: 'Even 1 spin-off is a significant project outcome. Track company stage (incorporated, funded, revenue-generating). Connect with incubators and accelerators early. Survival beyond 2 years is the key metric.',
    unit: 'number',
    aggregation_method: 'sum',
    data_source: 'manual',
    collection_frequency: 'annually',
    maturity_level: 'expert' as const,
    is_system: true,
    is_active: true,
    default_baseline: 0,
    default_target: 3,
  },
];
