/**
 * Static objective catalog — 36 professional CDE objectives as hardcoded data.
 * Used as primary data source until the SQL seed is run on Supabase.
 *
 * 12 objectives per domain (Communication, Dissemination, Exploitation)
 * covering all 7 outcome types across 3 maturity levels.
 */
import type { ObjectiveLibrary } from './objectiveLibraryService';

function makeId(code: string): string {
  return 'obj-' + code.toLowerCase().replace(/[^a-z0-9]/g, '-');
}

const now = new Date().toISOString();

export const OBJECTIVE_CATALOG: ObjectiveLibrary[] = [
  // ═══════════════════════════════════════════════════════
  // COMMUNICATION OBJECTIVES (12)
  // ═══════════════════════════════════════════════════════

  // ── Visibility ─────────────────────────────────────────
  {
    id: makeId('COM-VIS-01'),
    code: 'COM-VIS-01',
    title: 'Increase project visibility among target audiences',
    description: 'Raise awareness of the project, its goals, and expected outcomes among all identified target audiences through a coordinated mix of digital and traditional channels. Establish baseline awareness through stakeholder surveys and track reach, impressions, and recognition growth throughout the project lifecycle.',
    domain: 'communication',
    outcome_type: 'visibility',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'erasmus', 'interreg', 'generic'],
    default_stakeholder_types: ['policymakers', 'practitioners', 'researchers', 'general_public'],
    suggested_channel_types: ['website', 'social_media', 'events', 'newsletter'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-REACH-01', 'COM-REACH-02', 'COM-REACH-05'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('COM-VIS-02'),
    code: 'COM-VIS-02',
    title: 'Establish recognisable project brand identity',
    description: 'Develop and consistently apply a distinct visual and verbal brand identity (logo, messaging framework, tone of voice, templates) across all communication channels. Ensure brand guidelines are adopted by all consortium partners and measure brand recognition among target stakeholder groups at project mid-point and end.',
    domain: 'communication',
    outcome_type: 'visibility',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'erasmus', 'generic'],
    default_stakeholder_types: ['practitioners', 'industry', 'general_public'],
    suggested_channel_types: ['website', 'social_media', 'publications', 'events'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-REACH-01', 'COM-REACH-02', 'COM-PERCEP-01'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('COM-VIS-03'),
    code: 'COM-VIS-03',
    title: 'Achieve sustained media presence and coverage',
    description: 'Secure regular and meaningful coverage of project activities and results in relevant media outlets (trade press, academic media, mainstream media, sector-specific platforms). Develop journalist relationships, create press-ready materials, and track media mentions, reach, and sentiment to demonstrate growing public profile.',
    domain: 'communication',
    outcome_type: 'visibility',
    maturity_level: 'expert',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['media', 'policymakers', 'general_public'],
    suggested_channel_types: ['press_releases', 'media_events', 'social_media', 'publications'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-REACH-05', 'COM-PERCEP-01', 'COM-PERCEP-02'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Engagement ─────────────────────────────────────────
  {
    id: makeId('COM-ENG-01'),
    code: 'COM-ENG-01',
    title: 'Build an engaged online community',
    description: 'Create and grow an active online community around the project by publishing regular, relevant content that invites interaction. Set up appropriate social media channels, a project blog or news section, and a newsletter. Track engagement metrics (likes, shares, comments, newsletter open rates) and adapt content strategy based on what resonates with the audience.',
    domain: 'communication',
    outcome_type: 'engagement',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'erasmus', 'interreg', 'generic'],
    default_stakeholder_types: ['practitioners', 'researchers', 'general_public'],
    suggested_channel_types: ['social_media', 'newsletter', 'blog', 'website'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-ENGAGE-01', 'COM-ENGAGE-02', 'COM-ENGAGE-03'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('COM-ENG-02'),
    code: 'COM-ENG-02',
    title: 'Foster two-way dialogue with key stakeholders',
    description: 'Move beyond one-way broadcasting to establish genuine two-way communication with priority stakeholder groups. Design feedback mechanisms (surveys, consultation workshops, advisory boards, interactive webinars) that invite stakeholder input and demonstrate how it shapes project direction. Measure response rates, feedback quality, and stakeholder satisfaction.',
    domain: 'communication',
    outcome_type: 'engagement',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'erasmus', 'interreg', 'generic'],
    default_stakeholder_types: ['policymakers', 'practitioners', 'end_users'],
    suggested_channel_types: ['workshops', 'webinars', 'surveys', 'advisory_boards'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-ENGAGE-04', 'COM-ENGAGE-05', 'COM-MSG-01'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('COM-ENG-03'),
    code: 'COM-ENG-03',
    title: 'Create a stakeholder advocacy network',
    description: 'Identify and cultivate champion stakeholders who actively promote the project within their own networks. Develop an ambassador programme or stakeholder advocacy strategy where engaged stakeholders amplify project messages, co-create content, speak at events, and advocate to their peers. Track referral patterns, co-branded activities, and network multiplication effects.',
    domain: 'communication',
    outcome_type: 'engagement',
    maturity_level: 'expert',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['practitioners', 'industry', 'policymakers', 'civil_society'],
    suggested_channel_types: ['events', 'social_media', 'partnerships', 'co_publications'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-ENGAGE-04', 'COM-ENGAGE-05', 'COM-DIG-04'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Knowledge ──────────────────────────────────────────
  {
    id: makeId('COM-KNO-01'),
    code: 'COM-KNO-01',
    title: 'Raise awareness of project objectives and expected impact',
    description: 'Ensure that target audiences understand what the project aims to achieve and why it matters. Develop clear, jargon-free messaging about project goals and translate technical concepts into accessible language for different audience segments. Verify comprehension through stakeholder surveys and feedback.',
    domain: 'communication',
    outcome_type: 'knowledge',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'erasmus', 'interreg', 'generic'],
    default_stakeholder_types: ['policymakers', 'practitioners', 'researchers', 'general_public'],
    suggested_channel_types: ['website', 'factsheets', 'social_media', 'presentations'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-MSG-01', 'COM-MSG-02', 'COM-PERCEP-01'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('COM-KNO-02'),
    code: 'COM-KNO-02',
    title: 'Ensure key messages reach and resonate with target demographics',
    description: 'Develop a targeted messaging matrix that maps key messages to specific stakeholder segments. Test message effectiveness through A/B testing, focus groups, or sentiment analysis. Ensure each priority audience segment receives tailored messages through their preferred channels. Track message recall and comprehension rates.',
    domain: 'communication',
    outcome_type: 'knowledge',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'erasmus', 'generic'],
    default_stakeholder_types: ['policymakers', 'practitioners', 'industry', 'end_users'],
    suggested_channel_types: ['targeted_campaigns', 'social_media', 'email', 'events'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-MSG-01', 'COM-MSG-02', 'COM-PERCEP-02'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Capability ─────────────────────────────────────────
  {
    id: makeId('COM-CAP-01'),
    code: 'COM-CAP-01',
    title: 'Build internal communication capacity across the consortium',
    description: 'Equip all consortium partners with the skills, tools, and templates needed to communicate project activities consistently and effectively. Provide communication guidelines, brand assets, social media toolkits, and training sessions. Ensure every partner can represent the project accurately in their national and sectoral networks.',
    domain: 'communication',
    outcome_type: 'capability',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'erasmus', 'interreg', 'generic'],
    default_stakeholder_types: ['consortium_partners'],
    suggested_channel_types: ['training', 'toolkits', 'intranet', 'workshops'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-DIG-01', 'COM-DIG-02'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('COM-CAP-02'),
    code: 'COM-CAP-02',
    title: 'Develop partner communication competencies for national outreach',
    description: 'Go beyond basic guidelines to actively develop partners\u2019 strategic communication skills for their national contexts. Conduct localisation workshops, peer-learning sessions, and provide mentoring for partners who need additional support. Enable partners to independently design and execute national communication campaigns aligned with the project strategy.',
    domain: 'communication',
    outcome_type: 'capability',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'interreg', 'generic'],
    default_stakeholder_types: ['consortium_partners', 'national_agencies'],
    suggested_channel_types: ['training', 'workshops', 'mentoring', 'peer_learning'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-DIG-02', 'COM-DIG-03'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Sustainability ─────────────────────────────────────
  {
    id: makeId('COM-SUS-01'),
    code: 'COM-SUS-01',
    title: 'Ensure communication sustainability beyond project lifetime',
    description: 'Plan for the continuation of key communication activities after project funding ends. Identify which channels, content, and community relationships should be maintained, by whom, and with what resources. Create a communication legacy plan that includes content archiving, channel handover, and community stewardship arrangements.',
    domain: 'communication',
    outcome_type: 'sustainability',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'erasmus', 'generic'],
    default_stakeholder_types: ['consortium_partners', 'end_users', 'practitioners'],
    suggested_channel_types: ['website', 'social_media', 'newsletter', 'community_platform'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-DIG-04', 'COM-DIG-05'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('COM-SUS-02'),
    code: 'COM-SUS-02',
    title: 'Create a self-sustaining community platform',
    description: 'Design, build, and launch a community platform (online forum, community of practice, or network hub) that generates ongoing value for members beyond the project. Establish governance, moderation, and content strategies that enable the community to sustain itself through member contributions, partnerships, or institutional hosting after the project concludes.',
    domain: 'communication',
    outcome_type: 'sustainability',
    maturity_level: 'expert',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['practitioners', 'researchers', 'end_users', 'civil_society'],
    suggested_channel_types: ['community_platform', 'webinars', 'newsletter', 'events'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['COM-DIG-04', 'COM-DIG-05', 'COM-ENGAGE-05'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ═══════════════════════════════════════════════════════
  // DISSEMINATION OBJECTIVES (12)
  // ═══════════════════════════════════════════════════════

  // ── Knowledge ──────────────────────────────────────────
  {
    id: makeId('DIS-KNO-01'),
    code: 'DIS-KNO-01',
    title: 'Disseminate research results to the scientific community',
    description: 'Publish project findings in peer-reviewed journals, present at academic conferences, and contribute to open-access repositories. Ensure research results meet academic quality standards and are discoverable by the global research community. Track publication metrics (citations, downloads, h-index contribution) as evidence of scientific impact.',
    domain: 'dissemination',
    outcome_type: 'knowledge',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['researchers', 'academic_institutions'],
    suggested_channel_types: ['publications', 'conferences', 'open_access_repositories'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['DIS-KNO-01', 'DIS-KNO-02', 'DIS-KNO-03'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('DIS-KNO-02'),
    code: 'DIS-KNO-02',
    title: 'Transfer knowledge to practitioners and professionals',
    description: 'Bridge the gap between research findings and practical application by translating results into actionable guidance, best practice guides, toolkits, and case studies. Organise practitioner-focused events, workshops, and webinars that demonstrate how project outputs can solve real-world problems. Measure knowledge uptake through practitioner surveys and tool adoption rates.',
    domain: 'dissemination',
    outcome_type: 'knowledge',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'erasmus', 'interreg', 'generic'],
    default_stakeholder_types: ['practitioners', 'industry', 'sme'],
    suggested_channel_types: ['workshops', 'toolkits', 'webinars', 'case_studies'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['DIS-KNO-04', 'DIS-KNO-05', 'DIS-OUT-01'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('DIS-KNO-03'),
    code: 'DIS-KNO-03',
    title: 'Achieve cross-sector knowledge integration',
    description: 'Facilitate knowledge exchange between sectors that traditionally do not collaborate. Create cross-disciplinary synthesis reports, multi-stakeholder roundtables, and integration workshops that combine perspectives from academia, industry, policy, and civil society. Measure success through joint publications, cross-sector partnerships formed, and evidence of knowledge synthesis in downstream applications.',
    domain: 'dissemination',
    outcome_type: 'knowledge',
    maturity_level: 'expert',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['researchers', 'policymakers', 'industry', 'civil_society'],
    suggested_channel_types: ['roundtables', 'synthesis_reports', 'cross_sector_events'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['DIS-KNO-05', 'DIS-CAP-01', 'DIS-CAP-03'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Capability ─────────────────────────────────────────
  {
    id: makeId('DIS-CAP-01'),
    code: 'DIS-CAP-01',
    title: 'Build practitioner capacity through training materials',
    description: 'Develop a comprehensive set of training materials (online modules, video tutorials, reference guides, quick-start manuals) that enable practitioners to understand and apply project results independently. Design materials for self-paced learning and provide multiple formats for different learning preferences. Track completion rates, learner satisfaction, and skill improvement assessments.',
    domain: 'dissemination',
    outcome_type: 'capability',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'erasmus', 'interreg', 'generic'],
    default_stakeholder_types: ['practitioners', 'educators', 'trainers'],
    suggested_channel_types: ['e_learning', 'video_tutorials', 'manuals', 'workshops'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['DIS-CAP-01', 'DIS-CAP-02', 'DIS-CAP-03'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('DIS-CAP-02'),
    code: 'DIS-CAP-02',
    title: 'Develop professional development pathways',
    description: 'Design structured learning pathways that guide professionals from foundational to advanced competency in the project domain. Include mentoring programmes, train-the-trainer initiatives, and peer-learning networks. Create assessment frameworks to certify acquired skills. Measure competency progression, mentoring hours delivered, and trainer multiplication rates.',
    domain: 'dissemination',
    outcome_type: 'capability',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'erasmus', 'generic'],
    default_stakeholder_types: ['practitioners', 'educators', 'professional_associations'],
    suggested_channel_types: ['training_programmes', 'mentoring', 'certification', 'peer_learning'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['DIS-CAP-02', 'DIS-CAP-03', 'DIS-CAP-04'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('DIS-CAP-03'),
    code: 'DIS-CAP-03',
    title: 'Create an accredited training programme',
    description: 'Develop and accredit a formal training programme recognised by professional bodies or educational institutions. Ensure curriculum quality meets accreditation standards, recruit qualified instructors, establish examination processes, and award recognised credentials. Track enrolment, completion, certification rates, and employment outcomes for graduates.',
    domain: 'dissemination',
    outcome_type: 'capability',
    maturity_level: 'expert',
    programme_relevance: ['horizon', 'erasmus', 'generic'],
    default_stakeholder_types: ['educators', 'professional_associations', 'academic_institutions'],
    suggested_channel_types: ['accredited_courses', 'examinations', 'certification_bodies'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['DIS-CAP-03', 'DIS-CAP-04', 'DIS-CAP-05'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Visibility ─────────────────────────────────────────
  {
    id: makeId('DIS-VIS-01'),
    code: 'DIS-VIS-01',
    title: 'Maximise visibility and reach of project publications',
    description: 'Ensure all project publications (reports, papers, guides, policy briefs) are widely accessible and actively promoted. Implement open-access publishing, create dedicated landing pages for each major output, optimise for search engines, and run targeted promotion campaigns. Track downloads, page views, citations, and geographic distribution of readers.',
    domain: 'dissemination',
    outcome_type: 'visibility',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'erasmus', 'interreg', 'generic'],
    default_stakeholder_types: ['researchers', 'practitioners', 'policymakers'],
    suggested_channel_types: ['open_access', 'website', 'social_media', 'mailing_lists'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['DIS-OUT-01', 'DIS-OUT-02', 'DIS-KNO-01'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Engagement ─────────────────────────────────────────
  {
    id: makeId('DIS-ENG-01'),
    code: 'DIS-ENG-01',
    title: 'Engage practitioners in knowledge co-creation',
    description: 'Move beyond one-directional knowledge transfer to active co-creation with practitioners. Establish living labs, pilot sites, co-design workshops, and citizen science initiatives where practitioners contribute their expertise and validate project outputs. Track participation depth, co-authored outputs, and practitioner-led improvements to project deliverables.',
    domain: 'dissemination',
    outcome_type: 'engagement',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'interreg', 'generic'],
    default_stakeholder_types: ['practitioners', 'end_users', 'civil_society'],
    suggested_channel_types: ['living_labs', 'co_design_workshops', 'pilot_sites'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['DIS-CAP-01', 'DIS-KNO-04', 'DIS-KNO-05'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Adoption ───────────────────────────────────────────
  {
    id: makeId('DIS-ADO-01'),
    code: 'DIS-ADO-01',
    title: 'Promote adoption of project methodologies and tools',
    description: 'Actively promote the uptake of project-developed methodologies, frameworks, tools, and best practices among target user groups. Create easy-to-adopt implementation guides, provide onboarding support, collect user feedback, and iterate based on real-world use. Track adoption rates, active users, and user satisfaction over time.',
    domain: 'dissemination',
    outcome_type: 'adoption',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'erasmus', 'interreg', 'generic'],
    default_stakeholder_types: ['practitioners', 'industry', 'sme', 'public_sector'],
    suggested_channel_types: ['toolkits', 'onboarding', 'user_community', 'support_desk'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['DIS-OUT-03', 'DIS-OUT-04', 'DIS-OUT-05'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('DIS-ADO-02'),
    code: 'DIS-ADO-02',
    title: 'Achieve replication of project approach in new contexts',
    description: 'Enable other organisations, regions, or sectors to replicate the project approach in their own contexts. Create replication guides, document lessons learned, provide mentoring to replication sites, and build a network of implementers. Track number of replication initiatives launched, their fidelity to the original approach, and outcomes compared to the original.',
    domain: 'dissemination',
    outcome_type: 'adoption',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'interreg', 'generic'],
    default_stakeholder_types: ['practitioners', 'public_sector', 'ngo'],
    suggested_channel_types: ['replication_guides', 'mentoring', 'network_meetings'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['DIS-OUT-04', 'DIS-OUT-05', 'DIS-CAP-04'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Sustainability ─────────────────────────────────────
  {
    id: makeId('DIS-SUS-01'),
    code: 'DIS-SUS-01',
    title: 'Create sustainable open knowledge repositories',
    description: 'Establish long-term accessible repositories for all project knowledge assets (datasets, publications, training materials, tools, code). Ensure compliance with FAIR data principles, select institutional or community hosts with long-term sustainability, and define governance for ongoing curation. Track repository usage, citation, and data reuse metrics over time.',
    domain: 'dissemination',
    outcome_type: 'sustainability',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'erasmus', 'generic'],
    default_stakeholder_types: ['researchers', 'academic_institutions', 'data_stewards'],
    suggested_channel_types: ['open_access_repositories', 'data_portals', 'institutional_archives'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['DIS-OUT-01', 'DIS-OUT-02', 'DIS-KNO-03'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ═══════════════════════════════════════════════════════
  // EXPLOITATION OBJECTIVES (12)
  // ═══════════════════════════════════════════════════════

  // ── Adoption ───────────────────────────────────────────
  {
    id: makeId('EXP-ADO-01'),
    code: 'EXP-ADO-01',
    title: 'Secure initial adopters for project innovations',
    description: 'Identify, recruit, and support early adopters who commit to using project outputs (products, services, processes, or policies) in their operational context. Provide implementation support, collect structured feedback, and document early adoption case studies. Track number of adopters, time-to-adoption, and initial user satisfaction.',
    domain: 'exploitation',
    outcome_type: 'adoption',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['industry', 'sme', 'public_sector', 'end_users'],
    suggested_channel_types: ['pilot_programmes', 'demo_events', 'direct_outreach'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['EXP-UPT-01', 'EXP-UPT-02', 'EXP-UPT-03'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('EXP-ADO-02'),
    code: 'EXP-ADO-02',
    title: 'Achieve market readiness for key innovations',
    description: 'Advance project innovations from prototype or proof-of-concept stage to market-ready status (TRL 7-9). Conduct market validation studies, user acceptance testing, and regulatory compliance checks. Develop go-to-market strategies including pricing, distribution channels, and support models. Track TRL advancement, market validation milestones, and investor or customer interest signals.',
    domain: 'exploitation',
    outcome_type: 'adoption',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['industry', 'investors', 'sme', 'end_users'],
    suggested_channel_types: ['trade_fairs', 'investor_pitches', 'market_studies', 'pilot_sites'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['EXP-UPT-02', 'EXP-UPT-04', 'EXP-INT-01'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('EXP-ADO-03'),
    code: 'EXP-ADO-03',
    title: 'Scale adoption across multiple markets or regions',
    description: 'Expand from initial adopters to systematic, scaled adoption across multiple markets, regions, or sectors. Develop scalable business models, localisation strategies, and partnership networks for distribution. Establish performance benchmarks and quality assurance processes that maintain output quality at scale. Track geographic spread, volume growth, and market share metrics.',
    domain: 'exploitation',
    outcome_type: 'adoption',
    maturity_level: 'expert',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['industry', 'distributors', 'international_partners'],
    suggested_channel_types: ['distribution_partnerships', 'licensing', 'franchising', 'international_events'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['EXP-UPT-04', 'EXP-UPT-05', 'EXP-SUS-01'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Policy Influence ───────────────────────────────────
  {
    id: makeId('EXP-POL-01'),
    code: 'EXP-POL-01',
    title: 'Inform policy discussions with project evidence',
    description: 'Provide timely, relevant, and actionable evidence to policymakers and regulatory bodies. Produce policy briefs, position papers, and evidence summaries tailored to policy audiences. Participate in public consultations, parliamentary hearings, and policy roundtables. Track citations in policy documents, invitations to policy forums, and evidence of project findings entering policy discussions.',
    domain: 'exploitation',
    outcome_type: 'policy_influence',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'interreg', 'generic'],
    default_stakeholder_types: ['policymakers', 'regulators', 'government_agencies'],
    suggested_channel_types: ['policy_briefs', 'consultations', 'parliamentary_events', 'position_papers'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['EXP-POL-01', 'EXP-POL-02', 'EXP-POL-03'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('EXP-POL-02'),
    code: 'EXP-POL-02',
    title: 'Influence regulatory frameworks with project findings',
    description: 'Actively engage with regulatory processes to shape standards, guidelines, or regulations based on project evidence. Build relationships with standards bodies, contribute to working groups, submit formal responses to regulatory consultations, and collaborate with industry associations. Track contributions to standards documents, regulatory references to project work, and evidence of framework changes influenced.',
    domain: 'exploitation',
    outcome_type: 'policy_influence',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['regulators', 'standards_bodies', 'industry_associations'],
    suggested_channel_types: ['standards_committees', 'regulatory_consultations', 'industry_working_groups'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['EXP-POL-02', 'EXP-POL-03', 'EXP-POL-04'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('EXP-POL-03'),
    code: 'EXP-POL-03',
    title: 'Achieve measurable policy change based on project outcomes',
    description: 'Demonstrate direct, attributable impact on policy decisions at local, national, or EU level. Secure commitments from policymakers to implement recommendations, track policy adoption timelines, and document the causal pathway from project evidence to policy change. This is a transformational objective requiring sustained engagement over multiple policy cycles.',
    domain: 'exploitation',
    outcome_type: 'policy_influence',
    maturity_level: 'expert',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['policymakers', 'government_agencies', 'eu_institutions'],
    suggested_channel_types: ['high_level_events', 'ministerial_briefings', 'eu_policy_forums'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['EXP-POL-03', 'EXP-POL-04', 'EXP-POL-05'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Sustainability ─────────────────────────────────────
  {
    id: makeId('EXP-SUS-01'),
    code: 'EXP-SUS-01',
    title: 'Develop viable business models for project outputs',
    description: 'Explore and validate business models that can sustain project outputs beyond the funding period. Conduct market analysis, define value propositions, identify revenue streams (licensing, subscriptions, services, freemium), and test pricing with potential customers. Produce a business plan with financial projections and investment requirements.',
    domain: 'exploitation',
    outcome_type: 'sustainability',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['industry', 'investors', 'sme', 'end_users'],
    suggested_channel_types: ['business_planning', 'market_research', 'investor_meetings'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['EXP-SUS-01', 'EXP-SUS-02', 'EXP-INT-01'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('EXP-SUS-02'),
    code: 'EXP-SUS-02',
    title: 'Secure funding or partnerships for post-project continuation',
    description: 'Identify and pursue funding sources, institutional partnerships, or commercial agreements that ensure continuity of project activities and outputs after the EU funding period ends. Explore follow-on grants, industry sponsorship, institutional embedding, spin-off creation, or merger with existing organisations. Track funding applications, partnerships formalised, and resources committed.',
    domain: 'exploitation',
    outcome_type: 'sustainability',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'erasmus', 'interreg', 'generic'],
    default_stakeholder_types: ['funding_bodies', 'institutional_partners', 'investors'],
    suggested_channel_types: ['grant_applications', 'partnership_negotiations', 'investor_pitches'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['EXP-SUS-02', 'EXP-SUS-03', 'EXP-SUS-04'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: makeId('EXP-SUS-03'),
    code: 'EXP-SUS-03',
    title: 'Establish a self-sustaining commercial or institutional operation',
    description: 'Transform the most viable project outputs into a self-sustaining entity — whether a spin-off company, an institutional centre of excellence, or an industry consortium. Secure governance structures, ongoing financing, operational capacity, and market position. This is the highest exploitation ambition: proving that EU-funded innovation can stand on its own.',
    domain: 'exploitation',
    outcome_type: 'sustainability',
    maturity_level: 'expert',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['investors', 'industry', 'institutional_partners', 'board_members'],
    suggested_channel_types: ['spin_off_creation', 'institutional_embedding', 'industry_consortium'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['EXP-SUS-04', 'EXP-SUS-05', 'EXP-INT-03'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Capability ─────────────────────────────────────────
  {
    id: makeId('EXP-CAP-01'),
    code: 'EXP-CAP-01',
    title: 'Build adopter capacity for successful implementation',
    description: 'Ensure that organisations adopting project outputs have the skills, processes, and infrastructure needed for successful implementation. Provide implementation guides, technical support, change management resources, and troubleshooting assistance. Track adopter readiness assessments, support ticket resolution, and implementation success rates.',
    domain: 'exploitation',
    outcome_type: 'capability',
    maturity_level: 'basic',
    programme_relevance: ['horizon', 'erasmus', 'interreg', 'generic'],
    default_stakeholder_types: ['industry', 'sme', 'public_sector', 'practitioners'],
    suggested_channel_types: ['implementation_support', 'technical_assistance', 'training'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['EXP-UPT-01', 'EXP-UPT-02', 'EXP-INT-02'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },

  // ── Engagement ─────────────────────────────────────────
  {
    id: makeId('EXP-ENG-01'),
    code: 'EXP-ENG-01',
    title: 'Engage early adopters in continuous improvement cycles',
    description: 'Establish structured feedback loops with early adopters to continuously improve project outputs based on real-world use. Create user advisory groups, conduct regular satisfaction surveys, implement feature request processes, and run beta testing programmes. Track feedback volume, implementation rate of suggestions, and user satisfaction trends.',
    domain: 'exploitation',
    outcome_type: 'engagement',
    maturity_level: 'advanced',
    programme_relevance: ['horizon', 'generic'],
    default_stakeholder_types: ['end_users', 'industry', 'sme'],
    suggested_channel_types: ['user_groups', 'feedback_platforms', 'beta_programmes', 'surveys'],
    suggested_kpi_bundle_id: null,
    suggested_indicator_codes: ['EXP-UPT-03', 'EXP-INT-01', 'EXP-INT-02'],
    is_active: true,
    is_system: true,
    created_at: now,
    updated_at: now,
  },
];
