-- =========================================================
-- Seed 60 CDE Indicators into indicator_library
-- =========================================================
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor)
-- Safe to run multiple times - skips existing indicators
-- =========================================================

-- Step 1: Ensure code column has a unique constraint for ON CONFLICT
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE tablename = 'indicator_library' AND indexdef LIKE '%code%' AND indexdef LIKE '%UNIQUE%'
  ) THEN
    -- Check if there's already a unique constraint
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints tc
      JOIN information_schema.constraint_column_usage ccu ON tc.constraint_name = ccu.constraint_name
      WHERE tc.table_name = 'indicator_library' AND ccu.column_name = 'code' AND tc.constraint_type = 'UNIQUE'
    ) THEN
      CREATE UNIQUE INDEX IF NOT EXISTS idx_indicator_library_code_unique ON public.indicator_library (code);
      RAISE NOTICE 'Created unique index on indicator_library.code';
    END IF;
  END IF;
END $$;

-- Step 2: Disable RLS temporarily for this session (SQL Editor runs as postgres)
-- This allows us to insert system indicators without RLS restrictions

-- Step 3: Insert 60 CDE indicators
-- Communication (20)
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-REACH-01', 'Website Unique Visitors', 'Number of unique individuals visiting project website during reporting period, measured via analytics platform using cookie/session identification.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-REACH-02', 'Social Media Impressions', 'Total number of times project-related content appeared in social media feeds across all platforms (organic and paid), regardless of clicks or engagement.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-REACH-03', 'Event Participants (In-person)', 'Number of individuals physically attending project-organized or co-organized communication events, verified through registration systems or attendance records.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-REACH-04', 'Event Participants (Virtual)', 'Number of individuals attending project online events (webinars, virtual conferences, online workshops) tracked through platform analytics.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-REACH-05', 'Press Releases Distributed', 'Number of formal press releases issued through recognised distribution channels (wire services, institutional press offices, targeted media lists) during the reporting period.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-REACH-06', 'Media Mentions / Press Coverage', 'Number of distinct media articles, broadcasts, or online news pieces that mention the project by name or reference its key outputs, tracked via media monitoring services.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-ENG-01', 'Social Media Engagement Rate', 'Percentage of social media impressions that generated active engagement (likes, shares, comments, clicks) calculated as (total engagements / total impressions) x 100.', 'communication', 'percentage', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-ENG-02', 'Newsletter Open Rate', 'Percentage of delivered newsletters that were opened by recipients, calculated as (unique opens / delivered emails) x 100, tracked via email marketing platform.', 'communication', 'percentage', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-ENG-03', 'Average Session Duration (Website)', 'Mean time in minutes that visitors spend on project website per session, measured from landing to exit or timeout.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-ENG-04', 'Newsletter Click-Through Rate', 'Percentage of newsletter recipients who clicked at least one link within the email, calculated as (unique clicks / delivered emails) x 100, tracked via email marketing platform.', 'communication', 'percentage', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-ENG-05', 'Video Views', 'Total number of views of project-produced video content across all hosting platforms (YouTube, Vimeo, social media native video), counting views that exceed the platform minimum threshold.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-ENG-06', 'Content Shares / Amplification', 'Total number of times project content is shared, retweeted, reposted, or forwarded by external users across all digital platforms, indicating organic amplification by the audience.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-AUD-01', 'Stakeholder Group Diversity', 'Number of distinct stakeholder categories reached through communication activities, based on predefined taxonomy (policymakers, practitioners, researchers, industry, civil society, public, consortium).', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-PERC-01', 'Brand Recognition', 'Percentage of surveyed target audience members who can correctly identify project name, logo, or core message when prompted, measured via awareness survey.', 'communication', 'percentage', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-PERC-02', 'Message Comprehension', 'Percentage of event participants or survey respondents who can accurately explain core project message or value proposition in own words, assessed against rubric.', 'communication', 'percentage', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-DIG-01', 'Website Pages per Session', 'Average number of distinct pages viewed per visitor session on the project website, as reported by the web analytics platform.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-DIG-02', 'Social Media Follower Growth Rate', 'Percentage change in total social media followers across all project channels during the reporting period, calculated as ((new followers - unfollows) / starting followers) x 100.', 'communication', 'percentage', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-DIG-03', 'Multilingual Content Coverage', 'Number of languages in which key project communication materials (website, brochures, executive summaries) are made available, beyond the primary working language.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-MAT-01', 'Communication Materials Produced', 'Total number of distinct communication materials produced during the reporting period, including brochures, factsheets, posters, flyers, project briefs, and roll-up banners.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('COM-MAT-02', 'Infographics and Visual Assets Created', 'Number of professionally designed infographics, data visualisations, diagrams, or visual summary assets created to communicate project findings or processes to non-specialist audiences.', 'communication', 'number', true) ON CONFLICT (code) DO NOTHING;

-- Dissemination (20)
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-KNO-01', 'Knowledge Assets Published', 'Number of structured knowledge products published and made accessible to target audiences (publications, guidelines, toolkits, datasets, policy briefs, training materials).', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-KNO-02', 'Open Access Publications', 'Number of peer-reviewed publications made available via open access channels (Gold, Green, or Diamond OA) within 6 months of publication.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-KNO-03', 'Knowledge Asset Downloads', 'Total number of complete downloads of project knowledge products from project website, repositories, or publication platforms.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-KNO-04', 'Citations in External Publications', 'Number of times project outputs are cited in external scholarly publications, policy documents, or professional reports, tracked via citation databases.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-KNO-05', 'Policy Briefs Published', 'Number of concise, evidence-based policy briefs produced to translate project research findings into actionable recommendations for policymakers and institutional decision-makers.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-KNO-06', 'Best Practice Guides Produced', 'Number of structured best practice guides, handbooks, or implementation manuals published that synthesise project learnings into replicable methodologies for practitioners.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-KNO-07', 'Datasets Made Openly Available', 'Number of structured datasets deposited in recognised open data repositories (e.g., Zenodo, Figshare, national data portals) with FAIR-compliant metadata and persistent identifiers.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-KNO-08', 'Technical Standards Contributed To', 'Number of formal technical standards, norms, or specifications (ISO, CEN, W3C, ETSI, or equivalent) to which the project has made documented contributions or submissions.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-TRA-01', 'Training Sessions Delivered', 'Number of structured training activities delivered to target audiences (workshops, webinars, train-the-trainer sessions, masterclasses).', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-TRA-02', 'Trainees Reporting Improved Understanding', 'Percentage of training participants who report improved understanding of topic via post-training survey (5-point Likert scale, aggregating agree and strongly agree).', 'dissemination', 'percentage', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-TRA-03', 'Training Participants (Total)', 'Total number of individuals who participated in project-delivered training activities across all formats (in-person, virtual, blended), counted as unique participants per training event.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-TRA-04', 'Post-Training Application Rate', 'Percentage of training participants who report applying learned skills or knowledge in their professional practice within 6 months of training, measured via follow-up survey.', 'dissemination', 'percentage', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-TRA-05', 'Train-the-Trainer Multiplier Events', 'Number of training events delivered by individuals who were themselves trained by the project (second-generation or cascade training), indicating successful knowledge multiplication.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-OUT-01', 'Conference Presentations Delivered', 'Number of oral presentations, poster sessions, or demonstrations delivered at external conferences, symposia, or professional gatherings by project team members presenting project results.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-OUT-02', 'Invited Keynotes and Panels', 'Number of invited keynote speeches, panel participations, or expert roundtable contributions where project team members are specifically requested to share project expertise.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-OUT-03', 'Cross-Project Collaborations', 'Number of formal or substantive collaborations established with other funded projects (joint publications, shared events, co-developed outputs, clustering activities) during the reporting period.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-CAP-01', 'Reusable Tools/Frameworks Created', 'Number of operational tools, methodologies, or frameworks developed by project that are designed for replication/adaptation by external users (software, templates, assessment frameworks).', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-CAP-02', 'Stakeholder Networks Established', 'Number of formal or informal stakeholder networks, communities of practice, or professional groups established or significantly strengthened through project activities.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-CAP-03', 'Open Source Contributions', 'Number of software tools, libraries, or code repositories made publicly available under recognised open-source licences (Apache 2.0, MIT, GPL, EUPL) with documentation and maintenance commitment.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('DIS-CAP-04', 'Educational Curriculum Integrations', 'Number of formal integrations of project outputs into educational curricula at university, vocational, or professional development programme level, evidenced by syllabus references or course materials.', 'dissemination', 'number', true) ON CONFLICT (code) DO NOTHING;

-- Exploitation (20)
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-INT-01', 'Expressions of Interest', 'Number of documented, substantive expressions of interest from potential adopters, licensees, investors, or implementation partners regarding project outputs.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-INT-02', 'Formal Exploitation Agreements', 'Number of signed legal agreements for exploitation of project results (licensing, collaboration, commercialization, implementation contracts, spin-off creation).', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-INT-03', 'Letters of Support Collected', 'Number of formal letters of support, endorsement, or intent received from external organisations expressing commitment to use, adopt, or promote project results.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-INT-04', 'Pilot Adoption Agreements', 'Number of signed agreements with external organisations to pilot, test, or trial project outputs in their operational context, including memoranda of understanding and pilot protocols.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-IMP-01', 'Implementations in Operational Settings', 'Number of documented instances where project outputs are deployed in real-world operational settings beyond project pilots (public services, commercial products, policy frameworks).', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-IMP-02', 'Geographic Replication', 'Number of distinct countries or regions where project outputs have been adopted or adapted for implementation, beyond original project scope.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-IMP-03', 'Market Validation Studies Completed', 'Number of structured market analysis, feasibility study, or user needs assessment exercises completed to validate commercial or operational viability of project outputs.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-IMP-04', 'Technology Readiness Level Advancement', 'Number of TRL levels advanced by the primary project technology or innovation during the project lifecycle, measured against the EU-standard 9-level TRL scale at project start and end.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-IMP-05', 'User Adoption Rate', 'Percentage of target users within pilot or early-adopter organisations who actively use project outputs after initial deployment, measured at defined intervals post-introduction.', 'exploitation', 'percentage', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-POL-01', 'Policy References', 'Number of policy documents, strategies, regulations, or legislative texts that explicitly reference or incorporate project findings or recommendations.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-POL-02', 'Policy Consultations Participated In', 'Number of formal policy consultations, regulatory reviews, or governmental advisory processes in which project team members participated and submitted evidence or recommendations.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-POL-03', 'Standards Contributions Accepted', 'Number of project-originated contributions formally accepted into published or draft technical standards, norms, or regulatory frameworks by recognised standardisation bodies.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-ECO-01', 'Jobs Created/Safeguarded', 'Number of full-time equivalent (FTE) jobs created or safeguarded through commercial exploitation of project results (spin-offs, licensing leading to production, service delivery).', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-ECO-02', 'Revenue from Exploitation', 'Total revenue (EUR) generated through commercial exploitation of project intellectual property or results (licensing fees, sales, service contracts).', 'exploitation', 'currency', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-ECO-03', 'Investment / Funding Attracted Post-Project', 'Total value (EUR) of follow-on funding, venture capital, public grants, or institutional investment secured to further develop or scale project results after the initial funding period.', 'exploitation', 'currency', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-ECO-04', 'Cost Savings Demonstrated', 'Total documented cost savings (EUR) achieved by adopting organisations through implementation of project outputs, calculated against established baselines using agreed methodology.', 'exploitation', 'currency', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-ECO-05', 'Patents or IP Registrations Filed', 'Number of patent applications, trademark registrations, design rights, or other formal intellectual property protections filed based on project-generated innovations or outputs.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-SUS-01', 'Sustainability Plans Developed', 'Number of formal sustainability plans or business continuity strategies developed for key project outputs, specifying governance, funding models, and operational arrangements beyond the project period.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-SUS-02', 'Continuation Partnerships Secured', 'Number of formal partnership agreements secured with organisations committed to maintaining, scaling, or further developing project outputs after the funded period concludes.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.indicator_library (code, title, description, category, measurement_unit, is_approved) VALUES ('EXP-SUS-03', 'Spin-off Companies Created', 'Number of new legal entities (companies, cooperatives, social enterprises) established specifically to commercialise or operationalise project results, with direct lineage to project outputs.', 'exploitation', 'number', true) ON CONFLICT (code) DO NOTHING;

-- Step 4: Verify
SELECT category, count(*) as count FROM public.indicator_library GROUP BY category ORDER BY category;
