/*
  # Fix Strategy Tables RLS Policies

  1. Changes
    - Update all strategy-related tables to use current_profile_id() helper
    - Remove fragile subqueries that can return NULL and block operations
    - Ensure coordinators/admins can create, update, delete strategy data
    - All project members can read strategy data

  2. Tables Fixed
    - cde_strategies: Project-level strategy configurations
    - cde_strategy_objectives: Strategy-specific objectives
    - cde_strategy_channel_plan: Communication channel plans
    - cde_strategy_generated_items: Items generated by strategy builder

  3. Security
    - Uses current_profile_id() for safe profile ID resolution
    - Maintains project membership checks
    - Enforces role-based access (coordinator/admin for write operations)
    - No tenant isolation weakening

  4. Important Notes
    - Removes all (SELECT id FROM users WHERE auth_id = auth.uid()) subqueries
    - Policies properly check project membership via cde_strategies.project_id
    - Strategy child tables join through cde_strategies for security
*/

-- ============================================================
-- FIX CDE_STRATEGIES POLICIES
-- ============================================================

-- Drop existing cde_strategies policies
DROP POLICY IF EXISTS "Project members can read strategies" ON cde_strategies;
DROP POLICY IF EXISTS "Project coordinators can create strategies" ON cde_strategies;
DROP POLICY IF EXISTS "Project coordinators can update strategies" ON cde_strategies;
DROP POLICY IF EXISTS "Project coordinators can delete strategies" ON cde_strategies;

-- CREATE: Coordinators/admins can read strategies
CREATE POLICY "Project members can read strategies"
ON cde_strategies FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM project_memberships pm
    WHERE pm.project_id = cde_strategies.project_id
      AND pm.user_id = public.current_profile_id()
  )
);

-- INSERT: Coordinators/admins can create strategies
CREATE POLICY "Project coordinators can create strategies"
ON cde_strategies FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM project_memberships pm
    WHERE pm.project_id = cde_strategies.project_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);

-- UPDATE: Coordinators/admins can update strategies
CREATE POLICY "Project coordinators can update strategies"
ON cde_strategies FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM project_memberships pm
    WHERE pm.project_id = cde_strategies.project_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM project_memberships pm
    WHERE pm.project_id = cde_strategies.project_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);

-- DELETE: Coordinators/admins can delete strategies
CREATE POLICY "Project coordinators can delete strategies"
ON cde_strategies FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM project_memberships pm
    WHERE pm.project_id = cde_strategies.project_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);

-- ============================================================
-- FIX CDE_STRATEGY_OBJECTIVES POLICIES
-- ============================================================

-- Drop existing cde_strategy_objectives policies
DROP POLICY IF EXISTS "Project members can read strategy objectives" ON cde_strategy_objectives;
DROP POLICY IF EXISTS "Project coordinators can create strategy objectives" ON cde_strategy_objectives;
DROP POLICY IF EXISTS "Project coordinators can update strategy objectives" ON cde_strategy_objectives;
DROP POLICY IF EXISTS "Project coordinators can delete strategy objectives" ON cde_strategy_objectives;

-- SELECT: Project members can read strategy objectives
CREATE POLICY "Project members can read strategy objectives"
ON cde_strategy_objectives FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_objectives.strategy_id
      AND pm.user_id = public.current_profile_id()
  )
);

-- INSERT: Coordinators/admins can create strategy objectives
CREATE POLICY "Project coordinators can create strategy objectives"
ON cde_strategy_objectives FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_objectives.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);

-- UPDATE: Coordinators/admins can update strategy objectives
CREATE POLICY "Project coordinators can update strategy objectives"
ON cde_strategy_objectives FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_objectives.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_objectives.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);

-- DELETE: Coordinators/admins can delete strategy objectives
CREATE POLICY "Project coordinators can delete strategy objectives"
ON cde_strategy_objectives FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_objectives.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);

-- ============================================================
-- FIX CDE_STRATEGY_CHANNEL_PLAN POLICIES
-- ============================================================

-- Drop existing cde_strategy_channel_plan policies
DROP POLICY IF EXISTS "Project members can read channel plans" ON cde_strategy_channel_plan;
DROP POLICY IF EXISTS "Project coordinators can create channel plans" ON cde_strategy_channel_plan;
DROP POLICY IF EXISTS "Project coordinators can update channel plans" ON cde_strategy_channel_plan;
DROP POLICY IF EXISTS "Project coordinators can delete channel plans" ON cde_strategy_channel_plan;

-- SELECT: Project members can read channel plans
CREATE POLICY "Project members can read channel plans"
ON cde_strategy_channel_plan FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_channel_plan.strategy_id
      AND pm.user_id = public.current_profile_id()
  )
);

-- INSERT: Coordinators/admins can create channel plans
CREATE POLICY "Project coordinators can create channel plans"
ON cde_strategy_channel_plan FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_channel_plan.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);

-- UPDATE: Coordinators/admins can update channel plans
CREATE POLICY "Project coordinators can update channel plans"
ON cde_strategy_channel_plan FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_channel_plan.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_channel_plan.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);

-- DELETE: Coordinators/admins can delete channel plans
CREATE POLICY "Project coordinators can delete channel plans"
ON cde_strategy_channel_plan FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_channel_plan.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);

-- ============================================================
-- FIX CDE_STRATEGY_GENERATED_ITEMS POLICIES
-- ============================================================

-- Drop existing cde_strategy_generated_items policies
DROP POLICY IF EXISTS "Project members can read generated items" ON cde_strategy_generated_items;
DROP POLICY IF EXISTS "Project coordinators can create generated items" ON cde_strategy_generated_items;
DROP POLICY IF EXISTS "Project coordinators can update generated items" ON cde_strategy_generated_items;
DROP POLICY IF EXISTS "Project coordinators can delete generated items" ON cde_strategy_generated_items;

-- SELECT: Project members can read generated items
CREATE POLICY "Project members can read generated items"
ON cde_strategy_generated_items FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_generated_items.strategy_id
      AND pm.user_id = public.current_profile_id()
  )
);

-- INSERT: Coordinators/admins can create generated items
CREATE POLICY "Project coordinators can create generated items"
ON cde_strategy_generated_items FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_generated_items.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);

-- UPDATE: Coordinators/admins can update generated items (if needed)
CREATE POLICY "Project coordinators can update generated items"
ON cde_strategy_generated_items FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_generated_items.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_generated_items.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);

-- DELETE: Coordinators/admins can delete generated items
CREATE POLICY "Project coordinators can delete generated items"
ON cde_strategy_generated_items FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM cde_strategies s
    JOIN project_memberships pm ON pm.project_id = s.project_id
    WHERE s.strategy_id = cde_strategy_generated_items.strategy_id
      AND pm.user_id = public.current_profile_id()
      AND pm.role IN ('coordinator', 'admin')
  )
);
